name: Test and Deploy Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step One: Download the Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Installing Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installing dependencies (including pytest from requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      #  Running tests with coverage and generating XML report
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-branch --cov-report=xml

      #  Uploading coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  deploy:
    runs-on: ubuntu-latest
    needs: test   # deploy will only run if the tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/YoloService || (git clone https://github.com/tmeraslan/YoloService.git && cd YoloService)

            git reset --hard
            git pull origin main

            if [ ! -d "venv" ]; then
                sudo apt-get update
                sudo apt-get install -y python3-venv python3-pip
                python3 -m venv venv
            fi

            source venv/bin/activate
            pip install --upgrade pip
            if [ -f requirements.txt ]; then
                pip install -r requirements.txt
            fi

            sudo systemctl daemon-reload
            sudo systemctl restart yolo || sudo systemctl start yolo
