name: Run Tests

on:
  pull_request:
    branches: 
      - main

# Add permissions for Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r torch-requirements.txt
        pip install -r requirements.txt
        # Install pytest and coverage tools in case they're not in requirements.txt
        pip install pytest pytest-cov
        pip install allure-pytest

    #  Run tests with coverage report
    - name: Run tests with coverage
      run: |
        mkdir -p allure-results
        pytest --cov=app --cov-report=xml --cov-report=term-missing   --alluredir=allure-results tests/

    #  Upload coverage report to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}   
        file: ./coverage.xml
        fail_ci_if_error: true
    - name: Upload Allure results as artifact
      uses: actions/upload-artifact@v4
      if: always()  # Upload even if tests fail
      with:
          name: allure-results
          path: allure-results/
          retention-days: 30

  allure-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all Allure results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results
          path: allure-results-downloaded
          merge-multiple: false


      - name: Merge all results into single directory
        run: |
          mkdir -p allure-results
          for dir in allure-results-downloaded/*/; do
            if [ -d "$dir" ]; then
              cp -r "$dir"* allure-results/ 2>/dev/null || true
            fi
          done
          
      - name: Generate and Deploy Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
          keep_reports: 20
   
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}
          publish_dir: allure-history
  
 
